module.exports={
    //Product Model Validation Responses
    INVALID_TITLE:{'status':'failed','message':'Invalid TITTLE'},
    INVALID_BULLETPOINTS:{'status':'failed','message':'Invalid BULLETPOINTS'},
    INVALID_MRP:{'status':'failed','message':'Invalid MRP'},
    INVALID_SELLINGPRICE:{'status':'failed','message':'Invalid SELLING PRICE'},
    INVALID_IMAGES:{'status':'failed','message':'Invalid IMAGE'},
    INVALID_AMZURL:{'status':'failed','message':'Invalid AMAZON URL'},
    INVALID_SHORTURL:{'status':'failed','message':'Invalid SHORTURL'},
    INVALID_SELLERID:{'status':'failed','message':'Invalid SELLERID'},
    INVALID_AMZASIN:{'status':'failed','message':'Invalid AMZASIN'},
    INVALID_DESCRIPTION:{'status':'failed','message':'Invalid DESCRIPTION'},
    CANNOT_SAVE:{'status':'failed','message':'Cannot Save MONGO ERROR'},
    SAVE_SUCCESSFULL:{'status':'success','message':'Saved Successfully'},
    INVALID_ID:{'status':'failed','message':'Invalid ID'},
    INVALID_BID:{'status':'failed','message':'Invalid BIDVALUE'},
    INVALID_VIEWTARGET:{'status':'failed','message':'Invalid VIEW TARGET'},
    INVALID_KEYWORDS:{'status':'failed','message':'Invalid Keywords'},
    DELETE_SUCCESSFUL:{'status':'success','message':'Deleted Successfully'},
    DELETE_FAILED:{'status':'failed','message':'Deleted Failed, No products Found'},
    CANNOT_GET_PRODUCT:{'status':'failed','message':'Cannot get Product with that Id'},
    Authentication_REQUIRED:{'status code':'401','status':'failed','message':"Authentication required"},
    SUCCESSFULLY_UPDATED:{'status':'success','message':'Updated Successfully'},
    FAILED_TO_UPDATE:{'status':'failed','message':'Failed to Update'},
    UNABLE_TO_PRODUCTS:{'status':'failed','message':'Unable to get products'},
    NO_PRODUCTS:{'status':'failed','message':'No Products are Available'},
    INVALID_SELLINGTYPE:{'status':'failed','message':'Invalid SELLING TYPE'},
    UNABLE_TO_SAVEPRODUCT:{'status':'failed','message':'Unable to save the product'},

    //User Model Responses
    INVALIDEMAIL:{'status':'failed','message':'Invalid Email' },
    INVALIDROLE:{'status':'failed','message':'Invalid Role'},
    INVALIDDOB:{'status':'failed','message':'Invalid Dob'},
    INVALIDPHONENUMBER:{'status':'failed','message':'Invalid Phone Number'},
    INVALIDPASSWORD:{'status':'failed','message':'Invalid Password'},
    INVALIDUSERID:{'status':'failed','message':'Invalid User Id'},
    INVALIDFIRSTNAME:{'status':'failed','message':'Invalid First Name'},
    INVALIDLASTNAME:{'status':'failed','message':'Invalid Last Name'},
    CONFIRMPASSWORDMISMATCH:{'status':'failed','message':'Password and Confirm Password Mismatch'},
    UNABLE_TO_SIGNUP:{'status':'failed','message':'Unable To Signup'},
    USER_ALREADY_REGISTERED:{'status':'failed','message':'User Already Registered'},
    REGISTRATION_SUCCESS:{'status':'success','message':'Registered Successfully'},
    INVALIDUPDATE:{'status':'failed', 'message':"Cannot Update Data"},
    UNABLE_TO_GET_DATA:{'status':'failed','message':'Unable To Get Data'},
    UNABLE_TO_DELETEUSER:{'status':'failed','message':'Cannot Be Deleted'},
    UNABLE_TO_RESET:{'status':'failed' ,'message':'Cannot Be Processed'},
    VERIFICATION_CODE_MISSING:{'status':'failed','message':'Opt was Missing'},
    INVALID_REQUEST:{'status':'failed','message':'OTP expired'},
    RESET_SUCCESS:{'status':'success','message':'Successfully Reseted your Password'},
    PASSWORD_MISSING:{'status':'failed', 'message':'New Password is Missing'},
    INVALIDLOGIN:{'status':'unauthorized' ,'message':'email and password are not correct'},
    INVALIDLOGINEMAIL:{'status':'authorized','message':'Unable To Login'},
    LOGIN_SUCCESS:{'status':'successful','message':'login successfully'},
    USER_VERIFIED:{'status':'success','message':'User verified'},
    USER_NOT_FOUND:{'status':'failed','message':'User not found'},
    USER_DOES_NOT_EXIST:{'status':'failed','message':'User Doesnt Exist'},
    COMMAND_SUCCESS:{'status':'success','message':'Command accepted'},
    UPDATE_SUCCESS:{'status':'success','message':'Your data updated successfully'},

// ADDRESS model responses
    UNABLE_TO_ADD_ADDRESS:{'status':'failed','message':'Unable To add Address '},
    UNABLE_TO_DELETE_ADDRESS:{'status':'failed','message':'Cannot Be Deleted'}
}